import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Background } from "@/components/Background/background";
import Navbar from "@/components/Navbar/navbar";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.className} h-full antialiased`}>
      <body>
        <Background />

        <div className="relative min-h-screen flex flex-col items-center">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
